ThoR/Alloy/Delab/Quantification.lean
ThoR/Relation/Quantification.lean
ThoR/Shared/Syntax/Algebra/algExpr.lean
ThoR/Shared/Syntax/Relation/expr.lean
ThoR/Shared/Syntax/arrowOp.lean
ThoR/Shared/Syntax/formula.lean

usage of partial function definitions

removal of decreasing by admit

---

ThoR/Alloy/Syntax/AST.lean
ThoR/Alloy/Syntax/Signature.lean
ThoR/Alloy/Syntax/Signature/signatureFactDecl.lean
ThoR/Alloy/Syntax/property.lean
ThoR/Alloy/Syntax/specification.lean
ThoR/Shared/Syntax/Relation/expr.lean
ThoR/Shared/Syntax/formula.lean
ThoR/Test/Alloy/03_signature.lean
ThoR/Test/Alloy/03a_signature_facts.lean
ThoR/Test/Alloy/13_formula.lean

Adding Support for Signature facts.

17 signature facts

---

ThoR/Alloy/Elab.lean
ThoR/Alloy/Syntax/AST.lean
ThoR/Alloy/Syntax/OpenModule.lean
ThoR/Alloy/Syntax/OpenModule/openModule.lean
ThoR/Alloy/Syntax/OpenModule/openModuleHelper.lean
ThoR/Alloy/Syntax/specification.lean
ThoR/Test/Alloy/alloyBlockTests.lean

import modules (blocks) with open

---

ThoR/Alloy/Elab.lean
ThoR/Alloy/Syntax/AST.lean
ThoR/Alloy/Syntax/IgnoredSyntax/check.lean
ThoR/Alloy/Syntax/IgnoredSyntax/ignorable.lean
ThoR/Alloy/Syntax/IgnoredSyntax/run.lean
ThoR/Alloy/Syntax/alloyData.lean
ThoR/Alloy/Syntax/specification.lean
ThoR/Test/Alloy/alloyBlockTests.lean
ThoR/Test/Alloy/unitTests/t02_specification.lean
ThoR/Test/Alloy/unitTests/t15_ignored_specifications.lean

Compatibility: Ignore run and check

---

ThoR/Test/Alloy/unitTests/t06_signature_field.lean

add test for signature field name overload

---

ThoR/Test/Alloy/unitTests/t09a_constant.lean

id -> iden

---

README.md

34 readme known problem tabs

---

ThoR/Alloy/SymbolTable/SymbolTable.lean
ThoR/Shared/Syntax/Formula/formulaService.lean
ThoR/Test/Alloy/unitTests/t13_formula.lean

fix ifelse & easier getPredCalls

---

ThoR/Alloy/Syntax/IgnoredSyntax/check.lean
ThoR/Alloy/Syntax/IgnoredSyntax/run.lean
ThoR/Test/Alloy/unitTests/t15_ignored_specifications.lean

improved check and run syntax

---

ThoR/Alloy/Syntax/Predicate/predDecl.lean
ThoR/Alloy/Syntax/Signature/fieldDecl.lean
ThoR/Alloy/Syntax/Signature/sigDecl.lean
ThoR/Alloy/Syntax/Signature/signatureFactDecl.lean
ThoR/Alloy/Syntax/assertDecl.lean
ThoR/Alloy/Syntax/factDecl.lean
ThoR/Alloy/Syntax/property.lean
ThoR/Test/Alloy/unitTests/t03_signature.lean
ThoR/Test/Alloy/unitTests/t06_signature_field.lean
ThoR/Test/Alloy/unitTests/t10_fact_decl.lean
ThoR/Test/Alloy/unitTests/t11_assert_decl.lean
ThoR/Test/Alloy/unitTests/t14_predDecl.lean

56 predicate signames fieldnames factnames use extendedident

---

ThoR.lean
ThoR/Tactics.lean
ThoR/Tactics/fact.lean
ThoR/Test/Alloy/Tactics/family.lean

fact tactic

---

ThoR/Alloy/Elab.lean
ThoR/Test/Alloy/unitTests/t17_moduleVariables.lean

71 alloy elab module variables error message for modules with unbound module variables

---

ThoR/Alloy/Syntax/AST.lean

fix import type

---

ThoR/Shared/Syntax/Relation/Expr/exprService.lean

dot join type inference fix

---

ThoR/Alloy/Delab/Shared/Algebra/unAlgOp.lean
ThoR/Shared/Syntax/Algebra/AlgExpr/algExprService.lean
ThoR/Shared/Syntax/Formula/formulaService.lean

77 elab fix elaboration of card

---

ThoR/Alloy/Delab/Rel.lean
ThoR/Alloy/Delab/RelType.lean

Rel delaboration

---

ThoR/Alloy/Elab.lean
ThoR/Alloy/SymbolTable/SymbolTableService.lean
ThoR/Test/Alloy/alloyBlockTests.lean

all defs and axioms get the ThoR_TupleSet

---

ThoR/Alloy/Elab.lean
ThoR/Test/Alloy/unitTests/t17_moduleVariables.lean

72 alloy elab module variables list

---

ThoR/Alloy/Elab.lean
ThoR/Test/Alloy/unitTests/t18_creation.lean

[feature] create error reporting

---

ThoR/Alloy/SymbolTable/CommandDecl/commandDecl.lean
ThoR/Alloy/SymbolTable/CommandDecl/commandDeclService.lean
ThoR/Alloy/SymbolTable/SymbolTableService.lean

[refactor] isFact, isAssert, isDecl -> enumeration

---

ThoR/Alloy/Elab.lean
ThoR/Alloy/SymbolTable/CommandDecl/commandDecl.lean
ThoR/Alloy/SymbolTable/CommandDecl/commandDeclService.lean
ThoR/Alloy/SymbolTable/SymbolTableService.lean
ThoR/Alloy/Syntax/AST.lean
ThoR/Alloy/Syntax/Function/FunctionArg/functionArg.lean
ThoR/Alloy/Syntax/Function/FunctionArg/functionArgService.lean
ThoR/Alloy/Syntax/Function/FunctionDecl/functionDecl.lean
ThoR/Alloy/Syntax/Function/FunctionDecl/functionDeclService.lean
ThoR/Alloy/Syntax/specification.lean
ThoR/Relation/SubType.lean
ThoR/Shared/Syntax/Formula/formulaService.lean
ThoR/Shared/Syntax/TypeExpr/typeExprService.lean
ThoR/Test/Alloy/alloyBlockTests.lean
ThoR/Test/Alloy/unitTests/t19_functions.lean

67 alloy functions

---

ThoR/Alloy/Delab/DelaborationService.lean
ThoR/Test/Delab/Shared/Relation/binRelOp.lean

rm _root_ from delab

---

ThoR/Alloy/Syntax/IgnoredSyntax/comment.lean
ThoR/Alloy/Syntax/IgnoredSyntax/ignorable.lean
ThoR/Test/Alloy/unitTests/t18_comments.lean

alloy-comments

---

ThoR/Alloy/Elab.lean
ThoR/Alloy/SymbolTable/CommandDecl/commandDecl.lean
ThoR/Alloy/SymbolTable/SymbolTableService.lean
ThoR/Alloy/Syntax/Function/FunctionDecl/functionDecl.lean
ThoR/Alloy/Syntax/Function/FunctionDecl/functionDeclService.lean
ThoR/Alloy/Syntax/Function/FunctionIfDecl/functionIfDecl.lean
ThoR/Alloy/Syntax/Function/FunctionIfDecl/functionIfDeclService.lean
ThoR/Alloy/UnhygienicUnfolder.lean
ThoR/Shared/Syntax/Formula/formula.lean
ThoR/Shared/Syntax/Formula/formulaService.lean
ThoR/Test/Alloy/unitTests/t19_functions.lean

116 feature b x else y

---

ThoR/Alloy/Syntax/Function/FunctionDecl/functionDecl.lean
ThoR/Alloy/Syntax/Function/FunctionDecl/functionDeclService.lean

115 feature parentheses and brackets

---

ThoR/Alloy/SymbolTable/CommandDecl/commandDecl.lean
ThoR/Alloy/SymbolTable/CommandDecl/commandDeclService.lean
ThoR/Alloy/SymbolTable/SymbolTable.lean
ThoR/Alloy/SymbolTable/SymbolTableService.lean
ThoR/Alloy/Syntax/AssertDecl/assertDeclService.lean
ThoR/Alloy/Syntax/FactDecl/factDeclService.lean
ThoR/Alloy/Syntax/Function/FunctionDecl/functionDeclService.lean
ThoR/Alloy/Syntax/Predicate/PredArg/predArgService.lean
ThoR/Alloy/Syntax/Predicate/PredDecl/predDeclService.lean
ThoR/Shared/Syntax/ArrowOp/arrowOp.lean
ThoR/Shared/Syntax/ArrowOp/arrowOpService.lean
ThoR/Shared/Syntax/Formula/formulaService.lean
ThoR/Shared/Syntax/Relation/Expr/expr.lean
ThoR/Shared/Syntax/Relation/Expr/exprService.lean
ThoR/Shared/Syntax/TypeExpr/typeExprService.lean
ThoR/Test/Alloy/unitTests/t19_functions.lean

117 feature function call

---

ThoR/Alloy/SymbolTable/CommandDecl/commandDecl.lean
ThoR/Alloy/SymbolTable/SymbolTable.lean
ThoR/Alloy/SymbolTable/VarDecl/varDecl.lean
ThoR/Alloy/Syntax/Predicate/PredArg/predArg.lean

122 improve log

---

ThoR/Shared/Syntax/Formula/formulaService.lean

[fix] let is matched to no none

---

ThoR/Alloy/Elab/CreateCommand/createService.lean
ThoR/Alloy/Syntax/Function/FunctionIfDecl/functionIfDecl.lean
ThoR/Alloy/Syntax/Function/FunctionIfDecl/functionIfDeclService.lean
ThoR/Shared/Syntax/Formula/formula.lean

else needed

---

ThoR/Alloy/Elab/CreateCommand/createService.lean
ThoR/Alloy/Syntax/Function/FunctionIfDecl/functionIfDeclService.lean
ThoR/Shared/Syntax/Formula/formulaService.lean

126 [fix] unknown identifier '[anonymous]'

---

ThoR/Shared/Syntax/Formula/formulaService.lean
ThoR/Tactics/fact.lean
ThoR/Test/Alloy/grandpa2.lean

149 preds asserts and facts callable in blockless alloy
